// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kademliaMessage.proto

/*
Package protoMessages is a generated protocol buffer package.

It is generated from these files:
	kademliaMessage.proto

It has these top-level messages:
	KademliaMessage
	PingMessage
	FindContactMessage
	WrapperMessage
	Contact
*/
package protoMessages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_PING         MessageType = 0
	MessageType_FIND_CONTACT MessageType = 1
	MessageType_FIND_DATA    MessageType = 2
	MessageType_SEND_STORE   MessageType = 3
)

var MessageType_name = map[int32]string{
	0: "PING",
	1: "FIND_CONTACT",
	2: "FIND_DATA",
	3: "SEND_STORE",
}
var MessageType_value = map[string]int32{
	"PING":         0,
	"FIND_CONTACT": 1,
	"FIND_DATA":    2,
	"SEND_STORE":   3,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type KademliaMessage struct {
	KademliaID       *string      `protobuf:"bytes,1,req,name=kademliaID" json:"kademliaID,omitempty"`
	MethodType       *MessageType `protobuf:"varint,2,req,name=methodType,enum=protoMessages.MessageType" json:"methodType,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *KademliaMessage) Reset()                    { *m = KademliaMessage{} }
func (m *KademliaMessage) String() string            { return proto.CompactTextString(m) }
func (*KademliaMessage) ProtoMessage()               {}
func (*KademliaMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *KademliaMessage) GetKademliaID() string {
	if m != nil && m.KademliaID != nil {
		return *m.KademliaID
	}
	return ""
}

func (m *KademliaMessage) GetMethodType() MessageType {
	if m != nil && m.MethodType != nil {
		return *m.MethodType
	}
	return MessageType_PING
}

// Empty because we only get response if alive
type PingMessage struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PingMessage) Reset()                    { *m = PingMessage{} }
func (m *PingMessage) String() string            { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()               {}
func (*PingMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Message to find contacts, returns a "list" of contacts
type FindContactMessage struct {
	KademliaTargetId *string    `protobuf:"bytes,1,req,name=kademlia_target_id,json=kademliaTargetId" json:"kademlia_target_id,omitempty"`
	Contacts         []*Contact `protobuf:"bytes,2,rep,name=contacts" json:"contacts,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *FindContactMessage) Reset()                    { *m = FindContactMessage{} }
func (m *FindContactMessage) String() string            { return proto.CompactTextString(m) }
func (*FindContactMessage) ProtoMessage()               {}
func (*FindContactMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FindContactMessage) GetKademliaTargetId() string {
	if m != nil && m.KademliaTargetId != nil {
		return *m.KademliaTargetId
	}
	return ""
}

func (m *FindContactMessage) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

type WrapperMessage struct {
	MsgType   *MessageType `protobuf:"varint,1,req,name=msg_type,json=msgType,enum=protoMessages.MessageType" json:"msg_type,omitempty"`
	MessageId *int64       `protobuf:"varint,2,req,name=message_id,json=messageId" json:"message_id,omitempty"`
	// Types that are valid to be assigned to Message:
	//	*WrapperMessage_Msg_1
	//	*WrapperMessage_Msg_2
	Message          isWrapperMessage_Message `protobuf_oneof:"message"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *WrapperMessage) Reset()                    { *m = WrapperMessage{} }
func (m *WrapperMessage) String() string            { return proto.CompactTextString(m) }
func (*WrapperMessage) ProtoMessage()               {}
func (*WrapperMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isWrapperMessage_Message interface {
	isWrapperMessage_Message()
}

type WrapperMessage_Msg_1 struct {
	Msg_1 *PingMessage `protobuf:"bytes,3,opt,name=msg_1,json=msg1,oneof"`
}
type WrapperMessage_Msg_2 struct {
	Msg_2 *FindContactMessage `protobuf:"bytes,4,opt,name=msg_2,json=msg2,oneof"`
}

func (*WrapperMessage_Msg_1) isWrapperMessage_Message() {}
func (*WrapperMessage_Msg_2) isWrapperMessage_Message() {}

func (m *WrapperMessage) GetMessage() isWrapperMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *WrapperMessage) GetMsgType() MessageType {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return MessageType_PING
}

func (m *WrapperMessage) GetMessageId() int64 {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return 0
}

func (m *WrapperMessage) GetMsg_1() *PingMessage {
	if x, ok := m.GetMessage().(*WrapperMessage_Msg_1); ok {
		return x.Msg_1
	}
	return nil
}

func (m *WrapperMessage) GetMsg_2() *FindContactMessage {
	if x, ok := m.GetMessage().(*WrapperMessage_Msg_2); ok {
		return x.Msg_2
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*WrapperMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _WrapperMessage_OneofMarshaler, _WrapperMessage_OneofUnmarshaler, _WrapperMessage_OneofSizer, []interface{}{
		(*WrapperMessage_Msg_1)(nil),
		(*WrapperMessage_Msg_2)(nil),
	}
}

func _WrapperMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*WrapperMessage)
	// message
	switch x := m.Message.(type) {
	case *WrapperMessage_Msg_1:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Msg_1); err != nil {
			return err
		}
	case *WrapperMessage_Msg_2:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Msg_2); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("WrapperMessage.Message has unexpected type %T", x)
	}
	return nil
}

func _WrapperMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*WrapperMessage)
	switch tag {
	case 3: // message.msg_1
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PingMessage)
		err := b.DecodeMessage(msg)
		m.Message = &WrapperMessage_Msg_1{msg}
		return true, err
	case 4: // message.msg_2
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FindContactMessage)
		err := b.DecodeMessage(msg)
		m.Message = &WrapperMessage_Msg_2{msg}
		return true, err
	default:
		return false, nil
	}
}

func _WrapperMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*WrapperMessage)
	// message
	switch x := m.Message.(type) {
	case *WrapperMessage_Msg_1:
		s := proto.Size(x.Msg_1)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WrapperMessage_Msg_2:
		s := proto.Size(x.Msg_2)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Protobuf representation of Contact.go
type Contact struct {
	KademliaId       *string `protobuf:"bytes,1,req,name=kademlia_id,json=kademliaId" json:"kademlia_id,omitempty"`
	Address          *string `protobuf:"bytes,2,req,name=address" json:"address,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Contact) Reset()                    { *m = Contact{} }
func (m *Contact) String() string            { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()               {}
func (*Contact) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Contact) GetKademliaId() string {
	if m != nil && m.KademliaId != nil {
		return *m.KademliaId
	}
	return ""
}

func (m *Contact) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*KademliaMessage)(nil), "protoMessages.KademliaMessage")
	proto.RegisterType((*PingMessage)(nil), "protoMessages.PingMessage")
	proto.RegisterType((*FindContactMessage)(nil), "protoMessages.FindContactMessage")
	proto.RegisterType((*WrapperMessage)(nil), "protoMessages.WrapperMessage")
	proto.RegisterType((*Contact)(nil), "protoMessages.Contact")
	proto.RegisterEnum("protoMessages.MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("kademliaMessage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xd1, 0x4b, 0xbb, 0x50,
	0x14, 0x9e, 0xba, 0x1f, 0xce, 0xe3, 0x6f, 0x4b, 0x0e, 0x14, 0x12, 0x54, 0xe6, 0x93, 0x44, 0x0c,
	0x26, 0x04, 0xd1, 0xdb, 0x9a, 0x5b, 0x93, 0xc8, 0x0d, 0x27, 0xf4, 0x28, 0xb2, 0x7b, 0x31, 0x29,
	0xa7, 0x78, 0x25, 0xe8, 0x9f, 0xed, 0x6f, 0x09, 0xdd, 0x75, 0xb9, 0xed, 0xa1, 0x27, 0x8f, 0xdf,
	0xf9, 0xbe, 0x73, 0xbe, 0xf3, 0x5d, 0x38, 0x7d, 0x8f, 0x08, 0x4d, 0x3f, 0x92, 0xe8, 0x85, 0x32,
	0x16, 0xc5, 0x74, 0x98, 0x17, 0x59, 0x99, 0x61, 0xbf, 0xfe, 0x70, 0x8c, 0x99, 0x29, 0x9c, 0x3c,
	0xef, 0xf3, 0xf0, 0x12, 0xa0, 0x91, 0xba, 0x8e, 0x2e, 0x18, 0xa2, 0xa5, 0xf8, 0x2d, 0x04, 0x1f,
	0x00, 0x52, 0x5a, 0xbe, 0x65, 0x24, 0xf8, 0xca, 0xa9, 0x2e, 0x1a, 0xa2, 0x35, 0xb0, 0xcf, 0x87,
	0x7b, 0x63, 0x87, 0xbc, 0xa8, 0x18, 0x7e, 0x8b, 0x6d, 0xf6, 0x41, 0x5d, 0x26, 0x9b, 0x98, 0xb7,
	0xcd, 0x4f, 0xc0, 0x59, 0xb2, 0x21, 0x93, 0x6c, 0x53, 0x46, 0xeb, 0xb2, 0x31, 0x70, 0x0b, 0xd8,
	0xac, 0x0b, 0xcb, 0xa8, 0x88, 0x69, 0x19, 0x26, 0x84, 0x1b, 0xd1, 0x9a, 0x4e, 0x50, 0x37, 0x5c,
	0x82, 0x36, 0xf4, 0xd6, 0x5b, 0x3d, 0xd3, 0x45, 0x43, 0xb2, 0x54, 0xfb, 0xec, 0xc0, 0x0c, 0x1f,
	0xef, 0xef, 0x78, 0xe6, 0xb7, 0x00, 0x83, 0xd7, 0x22, 0xca, 0x73, 0x5a, 0x34, 0x4b, 0xef, 0xa0,
	0x97, 0xb2, 0x38, 0x2c, 0xab, 0x9b, 0x84, 0x3f, 0x6f, 0x92, 0x53, 0x16, 0x57, 0x05, 0x5e, 0x54,
	0x61, 0xd4, 0x78, 0xe5, 0xb1, 0x0a, 0x43, 0xf2, 0x15, 0x8e, 0xb8, 0x04, 0x47, 0xf0, 0xaf, 0x9a,
	0x3a, 0xd2, 0x25, 0x43, 0xb0, 0xd4, 0xa3, 0x91, 0xad, 0x2c, 0xe6, 0x1d, 0xbf, 0x9b, 0xb2, 0x78,
	0x84, 0xf7, 0x5b, 0x89, 0xad, 0x77, 0x6b, 0xc9, 0xf5, 0x81, 0xe4, 0x38, 0x2f, 0xae, 0xb4, 0x1f,
	0x15, 0x90, 0xf9, 0x66, 0xd3, 0x01, 0x99, 0x93, 0xf0, 0x0a, 0xd4, 0x5d, 0x9a, 0xbb, 0x18, 0x7f,
	0xdf, 0x93, 0xa0, 0x0e, 0x72, 0x44, 0x48, 0x41, 0x19, 0xab, 0xfd, 0x2b, 0x7e, 0xf3, 0x7b, 0x33,
	0x07, 0xb5, 0x75, 0x34, 0xf6, 0xa0, 0xbb, 0x74, 0xbd, 0x27, 0xad, 0x83, 0x1a, 0xfc, 0x9f, 0xb9,
	0x9e, 0x13, 0x4e, 0x16, 0x5e, 0x30, 0x9e, 0x04, 0x9a, 0x80, 0x7d, 0x50, 0x6a, 0xc4, 0x19, 0x07,
	0x63, 0x4d, 0xc4, 0x01, 0xc0, 0x6a, 0xea, 0x39, 0xe1, 0x2a, 0x58, 0xf8, 0x53, 0x4d, 0xfa, 0x09,
	0x00, 0x00, 0xff, 0xff, 0xf0, 0x21, 0x62, 0xb0, 0x8d, 0x02, 0x00, 0x00,
}
