// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kademliaMessage.proto

/*
Package ptp_dfs is a generated protocol buffer package.

It is generated from these files:
	kademliaMessage.proto

It has these top-level messages:
	KademliaMessage
*/
package ptp_dfs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_PING         MessageType = 0
	MessageType_FIND_CONTACT MessageType = 1
	MessageType_FIND_DATA    MessageType = 2
	MessageType_SEND_STORE   MessageType = 3
)

var MessageType_name = map[int32]string{
	0: "PING",
	1: "FIND_CONTACT",
	2: "FIND_DATA",
	3: "SEND_STORE",
}
var MessageType_value = map[string]int32{
	"PING":         0,
	"FIND_CONTACT": 1,
	"FIND_DATA":    2,
	"SEND_STORE":   3,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type KademliaMessage struct {
	KademliaID       *string      `protobuf:"bytes,1,req,name=kademliaID" json:"kademliaID,omitempty"`
	MethodType       *MessageType `protobuf:"varint,2,req,name=methodType,enum=ptp_dfs.MessageType" json:"methodType,omitempty"`
	MessageID        *int64       `protobuf:"varint,3,req,name=messageID" json:"messageID,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *KademliaMessage) Reset()                    { *m = KademliaMessage{} }
func (m *KademliaMessage) String() string            { return proto.CompactTextString(m) }
func (*KademliaMessage) ProtoMessage()               {}
func (*KademliaMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *KademliaMessage) GetKademliaID() string {
	if m != nil && m.KademliaID != nil {
		return *m.KademliaID
	}
	return ""
}

func (m *KademliaMessage) GetMethodType() MessageType {
	if m != nil && m.MethodType != nil {
		return *m.MethodType
	}
	return MessageType_PING
}

func (m *KademliaMessage) GetMessageID() int64 {
	if m != nil && m.MessageID != nil {
		return *m.MessageID
	}
	return 0
}

func init() {
	proto.RegisterType((*KademliaMessage)(nil), "ptp_dfs.KademliaMessage")
	proto.RegisterEnum("ptp_dfs.MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("kademliaMessage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0x4e, 0x4c, 0x49,
	0xcd, 0xcd, 0xc9, 0x4c, 0xf4, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x2f, 0x28, 0x29, 0x88, 0x4f, 0x49, 0x2b, 0x56, 0x6a, 0x65, 0xe4, 0xe2, 0xf7,
	0x46, 0x55, 0x22, 0x24, 0xc7, 0xc5, 0x05, 0xd3, 0xe5, 0xe9, 0x22, 0xc1, 0xa8, 0xc0, 0xa4, 0xc1,
	0x19, 0x84, 0x24, 0x22, 0x64, 0xc2, 0xc5, 0x95, 0x9b, 0x5a, 0x92, 0x91, 0x9f, 0x12, 0x52, 0x59,
	0x90, 0x2a, 0xc1, 0xa4, 0xc0, 0xa4, 0xc1, 0x67, 0x24, 0xa2, 0x07, 0x35, 0x51, 0x0f, 0x6a, 0x0a,
	0x48, 0x2e, 0x08, 0x49, 0x9d, 0x90, 0x0c, 0x17, 0x67, 0x2e, 0x44, 0xca, 0xd3, 0x45, 0x82, 0x59,
	0x81, 0x49, 0x83, 0x39, 0x08, 0x21, 0xa0, 0xe5, 0xc1, 0xc5, 0x8d, 0xa4, 0x51, 0x88, 0x83, 0x8b,
	0x25, 0xc0, 0xd3, 0xcf, 0x5d, 0x80, 0x41, 0x48, 0x80, 0x8b, 0xc7, 0xcd, 0xd3, 0xcf, 0x25, 0xde,
	0xd9, 0xdf, 0x2f, 0xc4, 0xd1, 0x39, 0x44, 0x80, 0x51, 0x88, 0x97, 0x8b, 0x13, 0x2c, 0xe2, 0xe2,
	0x18, 0xe2, 0x28, 0xc0, 0x24, 0xc4, 0xc7, 0xc5, 0x15, 0xec, 0xea, 0xe7, 0x12, 0x1f, 0x1c, 0xe2,
	0x1f, 0xe4, 0x2a, 0xc0, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xa5, 0xe6, 0xa4, 0xf2, 0x00,
	0x00, 0x00,
}
