// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protoMessages.proto

/*
Package protoMessages is a generated protocol buffer package.

It is generated from these files:
	protoMessages.proto

It has these top-level messages:
	WrapperMessage
	PingMessage
	LookupContactMessage
	ProtoContact
	LookupDataMessage
	StoreMessage
*/
package protoMessages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Enum For Message Types
type MessageType int32

const (
	MessageType_PING         MessageType = 0
	MessageType_FIND_CONTACT MessageType = 1
	MessageType_FIND_DATA    MessageType = 2
	MessageType_SEND_STORE   MessageType = 3
)

var MessageType_name = map[int32]string{
	0: "PING",
	1: "FIND_CONTACT",
	2: "FIND_DATA",
	3: "SEND_STORE",
}
var MessageType_value = map[string]int32{
	"PING":         0,
	"FIND_CONTACT": 1,
	"FIND_DATA":    2,
	"SEND_STORE":   3,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Common wrapper for all 4 types of messages
type WrapperMessage struct {
	MessageType      MessageType `protobuf:"varint,1,opt,name=message_type,json=messageType,enum=protoMessages.MessageType" json:"message_type,omitempty"`
	RequestId        int64       `protobuf:"varint,2,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	SenderKademliaId string      `protobuf:"bytes,3,opt,name=sender_kademlia_id,json=senderKademliaId" json:"sender_kademlia_id,omitempty"`
	IsReply          bool        `protobuf:"varint,4,opt,name=is_reply,json=isReply" json:"is_reply,omitempty"`
	// Types that are valid to be assigned to Messages:
	//	*WrapperMessage_Msg_1
	//	*WrapperMessage_Msg_2
	//	*WrapperMessage_Msg_3
	//	*WrapperMessage_Msg_4
	Messages isWrapperMessage_Messages `protobuf_oneof:"messages"`
}

func (m *WrapperMessage) Reset()                    { *m = WrapperMessage{} }
func (m *WrapperMessage) String() string            { return proto.CompactTextString(m) }
func (*WrapperMessage) ProtoMessage()               {}
func (*WrapperMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isWrapperMessage_Messages interface {
	isWrapperMessage_Messages()
}

type WrapperMessage_Msg_1 struct {
	Msg_1 *PingMessage `protobuf:"bytes,5,opt,name=msg_1,json=msg1,oneof"`
}
type WrapperMessage_Msg_2 struct {
	Msg_2 *LookupContactMessage `protobuf:"bytes,6,opt,name=msg_2,json=msg2,oneof"`
}
type WrapperMessage_Msg_3 struct {
	Msg_3 *LookupDataMessage `protobuf:"bytes,7,opt,name=msg_3,json=msg3,oneof"`
}
type WrapperMessage_Msg_4 struct {
	Msg_4 *StoreMessage `protobuf:"bytes,8,opt,name=msg_4,json=msg4,oneof"`
}

func (*WrapperMessage_Msg_1) isWrapperMessage_Messages() {}
func (*WrapperMessage_Msg_2) isWrapperMessage_Messages() {}
func (*WrapperMessage_Msg_3) isWrapperMessage_Messages() {}
func (*WrapperMessage_Msg_4) isWrapperMessage_Messages() {}

func (m *WrapperMessage) GetMessages() isWrapperMessage_Messages {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *WrapperMessage) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_PING
}

func (m *WrapperMessage) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *WrapperMessage) GetSenderKademliaId() string {
	if m != nil {
		return m.SenderKademliaId
	}
	return ""
}

func (m *WrapperMessage) GetIsReply() bool {
	if m != nil {
		return m.IsReply
	}
	return false
}

func (m *WrapperMessage) GetMsg_1() *PingMessage {
	if x, ok := m.GetMessages().(*WrapperMessage_Msg_1); ok {
		return x.Msg_1
	}
	return nil
}

func (m *WrapperMessage) GetMsg_2() *LookupContactMessage {
	if x, ok := m.GetMessages().(*WrapperMessage_Msg_2); ok {
		return x.Msg_2
	}
	return nil
}

func (m *WrapperMessage) GetMsg_3() *LookupDataMessage {
	if x, ok := m.GetMessages().(*WrapperMessage_Msg_3); ok {
		return x.Msg_3
	}
	return nil
}

func (m *WrapperMessage) GetMsg_4() *StoreMessage {
	if x, ok := m.GetMessages().(*WrapperMessage_Msg_4); ok {
		return x.Msg_4
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*WrapperMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _WrapperMessage_OneofMarshaler, _WrapperMessage_OneofUnmarshaler, _WrapperMessage_OneofSizer, []interface{}{
		(*WrapperMessage_Msg_1)(nil),
		(*WrapperMessage_Msg_2)(nil),
		(*WrapperMessage_Msg_3)(nil),
		(*WrapperMessage_Msg_4)(nil),
	}
}

func _WrapperMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*WrapperMessage)
	// messages
	switch x := m.Messages.(type) {
	case *WrapperMessage_Msg_1:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Msg_1); err != nil {
			return err
		}
	case *WrapperMessage_Msg_2:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Msg_2); err != nil {
			return err
		}
	case *WrapperMessage_Msg_3:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Msg_3); err != nil {
			return err
		}
	case *WrapperMessage_Msg_4:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Msg_4); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("WrapperMessage.Messages has unexpected type %T", x)
	}
	return nil
}

func _WrapperMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*WrapperMessage)
	switch tag {
	case 5: // messages.msg_1
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PingMessage)
		err := b.DecodeMessage(msg)
		m.Messages = &WrapperMessage_Msg_1{msg}
		return true, err
	case 6: // messages.msg_2
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LookupContactMessage)
		err := b.DecodeMessage(msg)
		m.Messages = &WrapperMessage_Msg_2{msg}
		return true, err
	case 7: // messages.msg_3
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LookupDataMessage)
		err := b.DecodeMessage(msg)
		m.Messages = &WrapperMessage_Msg_3{msg}
		return true, err
	case 8: // messages.msg_4
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StoreMessage)
		err := b.DecodeMessage(msg)
		m.Messages = &WrapperMessage_Msg_4{msg}
		return true, err
	default:
		return false, nil
	}
}

func _WrapperMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*WrapperMessage)
	// messages
	switch x := m.Messages.(type) {
	case *WrapperMessage_Msg_1:
		s := proto.Size(x.Msg_1)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WrapperMessage_Msg_2:
		s := proto.Size(x.Msg_2)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WrapperMessage_Msg_3:
		s := proto.Size(x.Msg_3)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WrapperMessage_Msg_4:
		s := proto.Size(x.Msg_4)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Sub-header to ping a contact
type PingMessage struct {
}

func (m *PingMessage) Reset()                    { *m = PingMessage{} }
func (m *PingMessage) String() string            { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()               {}
func (*PingMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Sub-header to find contacts, returns a "list" of contacts
type LookupContactMessage struct {
	KademliaTargetId string          `protobuf:"bytes,1,opt,name=kademlia_target_id,json=kademliaTargetId" json:"kademlia_target_id,omitempty"`
	Contacts         []*ProtoContact `protobuf:"bytes,2,rep,name=contacts" json:"contacts,omitempty"`
}

func (m *LookupContactMessage) Reset()                    { *m = LookupContactMessage{} }
func (m *LookupContactMessage) String() string            { return proto.CompactTextString(m) }
func (*LookupContactMessage) ProtoMessage()               {}
func (*LookupContactMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LookupContactMessage) GetKademliaTargetId() string {
	if m != nil {
		return m.KademliaTargetId
	}
	return ""
}

func (m *LookupContactMessage) GetContacts() []*ProtoContact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

// Protobuf representation of Contact.go
type ProtoContact struct {
	KademliaId string `protobuf:"bytes,1,opt,name=kademlia_id,json=kademliaId" json:"kademlia_id,omitempty"`
	Address    string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *ProtoContact) Reset()                    { *m = ProtoContact{} }
func (m *ProtoContact) String() string            { return proto.CompactTextString(m) }
func (*ProtoContact) ProtoMessage()               {}
func (*ProtoContact) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ProtoContact) GetKademliaId() string {
	if m != nil {
		return m.KademliaId
	}
	return ""
}

func (m *ProtoContact) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// Sub-header to find data with a certain id, returns closer contacts if it wasn't found
type LookupDataMessage struct {
	KademliaTargetId string          `protobuf:"bytes,1,opt,name=kademlia_target_id,json=kademliaTargetId" json:"kademlia_target_id,omitempty"`
	Contacts         []*ProtoContact `protobuf:"bytes,2,rep,name=contacts" json:"contacts,omitempty"`
}

func (m *LookupDataMessage) Reset()                    { *m = LookupDataMessage{} }
func (m *LookupDataMessage) String() string            { return proto.CompactTextString(m) }
func (*LookupDataMessage) ProtoMessage()               {}
func (*LookupDataMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LookupDataMessage) GetKademliaTargetId() string {
	if m != nil {
		return m.KademliaTargetId
	}
	return ""
}

func (m *LookupDataMessage) GetContacts() []*ProtoContact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

// Sub-header to share where a nodes shared data can be found
type StoreMessage struct {
	KeyStore   string `protobuf:"bytes,1,opt,name=key_store,json=keyStore" json:"key_store,omitempty"`
	ValueStore string `protobuf:"bytes,2,opt,name=value_store,json=valueStore" json:"value_store,omitempty"`
	LifeTime   string `protobuf:"bytes,3,opt,name=life_time,json=lifeTime" json:"life_time,omitempty"`
}

func (m *StoreMessage) Reset()                    { *m = StoreMessage{} }
func (m *StoreMessage) String() string            { return proto.CompactTextString(m) }
func (*StoreMessage) ProtoMessage()               {}
func (*StoreMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *StoreMessage) GetKeyStore() string {
	if m != nil {
		return m.KeyStore
	}
	return ""
}

func (m *StoreMessage) GetValueStore() string {
	if m != nil {
		return m.ValueStore
	}
	return ""
}

func (m *StoreMessage) GetLifeTime() string {
	if m != nil {
		return m.LifeTime
	}
	return ""
}

func init() {
	proto.RegisterType((*WrapperMessage)(nil), "protoMessages.WrapperMessage")
	proto.RegisterType((*PingMessage)(nil), "protoMessages.PingMessage")
	proto.RegisterType((*LookupContactMessage)(nil), "protoMessages.LookupContactMessage")
	proto.RegisterType((*ProtoContact)(nil), "protoMessages.ProtoContact")
	proto.RegisterType((*LookupDataMessage)(nil), "protoMessages.LookupDataMessage")
	proto.RegisterType((*StoreMessage)(nil), "protoMessages.StoreMessage")
	proto.RegisterEnum("protoMessages.MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("protoMessages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0xc1, 0x8f, 0x93, 0x40,
	0x14, 0xc6, 0x97, 0xd2, 0xdd, 0xc2, 0xa3, 0x6d, 0x70, 0xf4, 0x80, 0x36, 0x46, 0x52, 0x2f, 0xc4,
	0x98, 0x4d, 0xda, 0x6e, 0xb2, 0x89, 0x89, 0x87, 0xda, 0xae, 0x2e, 0x51, 0xbb, 0x0d, 0x25, 0xf1,
	0x48, 0xc6, 0xe5, 0x49, 0x08, 0xa5, 0x20, 0x43, 0x4d, 0x30, 0xf1, 0x6f, 0xf1, 0x5f, 0x35, 0xcc,
	0x4c, 0x77, 0x61, 0xb7, 0x67, 0x6f, 0xf3, 0xbe, 0xef, 0xfd, 0x98, 0x79, 0xdf, 0x0c, 0xf0, 0x34,
	0x2f, 0xb2, 0x32, 0xfb, 0x8a, 0x8c, 0xd1, 0x08, 0xd9, 0x39, 0xaf, 0xc8, 0xa0, 0x25, 0x8e, 0xff,
	0xaa, 0x30, 0xfc, 0x56, 0xd0, 0x3c, 0xc7, 0x42, 0x6a, 0xe4, 0x3d, 0xf4, 0x53, 0xb1, 0x0c, 0xca,
	0x2a, 0x47, 0x4b, 0xb1, 0x15, 0x67, 0x38, 0x7d, 0x71, 0xde, 0xfe, 0x9a, 0x5c, 0xf8, 0x55, 0x8e,
	0x9e, 0x91, 0xde, 0x17, 0xe4, 0x25, 0x40, 0x81, 0x3f, 0xf7, 0xc8, 0xca, 0x20, 0x0e, 0xad, 0x8e,
	0xad, 0x38, 0xaa, 0xa7, 0x4b, 0xc5, 0x0d, 0xc9, 0x5b, 0x20, 0x0c, 0x77, 0x21, 0x16, 0x41, 0x42,
	0x43, 0x4c, 0xb7, 0x31, 0xad, 0xdb, 0x54, 0x5b, 0x71, 0x74, 0xcf, 0x14, 0xce, 0x67, 0x69, 0xb8,
	0x21, 0x79, 0x0e, 0x5a, 0xcc, 0x82, 0x02, 0xf3, 0x6d, 0x65, 0x75, 0x6d, 0xc5, 0xd1, 0xbc, 0x5e,
	0xcc, 0xbc, 0xba, 0x24, 0x13, 0x38, 0x4d, 0x59, 0x14, 0x4c, 0xac, 0x53, 0x5b, 0x71, 0x8c, 0x47,
	0xe7, 0x5b, 0xc7, 0xbb, 0x48, 0x16, 0xd7, 0x27, 0x5e, 0x37, 0x65, 0xd1, 0x84, 0xbc, 0x13, 0xc8,
	0xd4, 0x3a, 0xe3, 0xc8, 0xeb, 0x07, 0xc8, 0x97, 0x2c, 0x4b, 0xf6, 0xf9, 0x22, 0xdb, 0x95, 0xf4,
	0xb6, 0x6c, 0xb3, 0x53, 0x72, 0x29, 0xd8, 0x99, 0xd5, 0xe3, 0xac, 0x7d, 0x94, 0x5d, 0xd2, 0x92,
	0xb6, 0xc1, 0x19, 0x99, 0x0a, 0xf0, 0xc2, 0xd2, 0x38, 0x38, 0x7a, 0x00, 0x6e, 0xca, 0xac, 0xc0,
	0x36, 0x73, 0xf1, 0x01, 0x40, 0x4b, 0x0f, 0x37, 0x34, 0x00, 0xa3, 0x31, 0xcb, 0xf8, 0x0f, 0x3c,
	0x3b, 0x76, 0xce, 0x3a, 0xd7, 0xbb, 0x40, 0x4b, 0x5a, 0x44, 0xc8, 0xe3, 0x57, 0x44, 0xae, 0x07,
	0xc7, 0xe7, 0x86, 0x1b, 0x92, 0x4b, 0xd0, 0x6e, 0x05, 0xcf, 0xac, 0x8e, 0xad, 0x1e, 0x39, 0xd7,
	0xba, 0xae, 0xe4, 0x1e, 0xde, 0x5d, 0xf3, 0xd8, 0x85, 0x7e, 0xd3, 0x21, 0xaf, 0xc0, 0x68, 0xde,
	0xa3, 0xd8, 0x0f, 0x92, 0xfb, 0x1b, 0xb4, 0xa0, 0x47, 0xc3, 0xb0, 0x40, 0xc6, 0xf8, 0x5b, 0xd0,
	0xbd, 0x43, 0x39, 0xfe, 0x0d, 0x4f, 0x1e, 0xa5, 0xf6, 0xbf, 0xc6, 0x88, 0xa1, 0xdf, 0x0c, 0x9e,
	0x8c, 0x40, 0x4f, 0xb0, 0x0a, 0x58, 0xad, 0xc9, 0xdd, 0xb4, 0x04, 0x2b, 0xde, 0x53, 0xcf, 0xf8,
	0x8b, 0x6e, 0xf7, 0x28, 0x6d, 0x31, 0x06, 0x70, 0x49, 0x34, 0x8c, 0x40, 0xdf, 0xc6, 0x3f, 0x30,
	0x28, 0xe3, 0x14, 0xe5, 0x53, 0xd6, 0x6a, 0xc1, 0x8f, 0x53, 0x7c, 0x73, 0x0d, 0x46, 0xe3, 0x5f,
	0x21, 0x1a, 0x74, 0xd7, 0xee, 0xea, 0x93, 0x79, 0x42, 0x4c, 0xe8, 0x7f, 0x74, 0x57, 0xcb, 0x60,
	0x71, 0xb3, 0xf2, 0xe7, 0x0b, 0xdf, 0x54, 0xc8, 0x00, 0x74, 0xae, 0x2c, 0xe7, 0xfe, 0xdc, 0xec,
	0x90, 0x21, 0xc0, 0xe6, 0x6a, 0xb5, 0x0c, 0x36, 0xfe, 0x8d, 0x77, 0x65, 0xaa, 0xdf, 0xcf, 0xf8,
	0x68, 0xb3, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x58, 0x2b, 0xb4, 0xad, 0xd8, 0x03, 0x00, 0x00,
}
